name: test
on:
- pull_request
jobs:
  xenial:
    container: 
      image: swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  bionic:
    container: 
      image: swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  thread:
    container: 
      image: swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --sanitize=thread
